name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # update at 00:00 UTC 
  workflow_dispatch:      
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Generate languages SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: doloMing
          template: classic
          repositories_affiliations: owner, collaborator, organization_member
          
          filename: github-metrics.svg

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage,bytes-size
          plugin_languages_threshold: 1%
          plugin_languages_other: yes
          plugin_languages_ignored: html, css, jupyter notebook
